# Generated by Django 5.2.10 on 2026-02-04 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='student',
        ),
    ]
